/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());




        BinarySearchTree<Integer> test = new BinarySearchTree<>(5);
        test.root.leftChild=new Node<>(3);
        test.root.rightChild=new Node<>(6);
        test.root.leftChild.leftChild=new Node<>(2);
        test.root.leftChild.rightChild=new Node<>(4);


        test.add(1);



        System.out.println(test.contains(3,test.root));

        System.out.println(test.inOrder(test.root).toString());

    }
}
