/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }



    @Test void BinaryTreeTest(){

        BinaryTree<Integer> testBinary = new BinaryTree<>();
        assertNull(testBinary.root);


        BinaryTree<Integer> testBinary2 = new BinaryTree<>(1);
        assertEquals(1,testBinary2.root.value);


        testBinary2.root.leftChild = new Node<>(3);
        testBinary2.root.rightChild = new Node<>(5);
        assertEquals(3,testBinary2.root.leftChild.value);
        assertEquals(5,testBinary2.root.rightChild.value);


        assertEquals("[1, 3, 5]",testBinary2.preOrder(testBinary2.root).toString());



        assertEquals("[3, 1, 5]",testBinary2.inOrder(testBinary2.root).toString());



        assertEquals("[3, 5, 1]",testBinary2.postOrder(testBinary2.root).toString());

    }
}
