/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());




        BinarySearchTree<Integer> maxTest = new BinarySearchTree<>(5);
        maxTest.root.leftChild=new Node<>(8);
        maxTest.root.rightChild=new Node<>(10);
        maxTest.root.leftChild.leftChild=new Node<>(1);
        maxTest.root.leftChild.rightChild=new Node<>(3);

        System.out.println(maxTest.maximum());

//        test.add(1);
//
//
//
//        System.out.println(test.contains(3,test.root));
//
//        System.out.println(test.inOrder(test.root).toString());

    }
}
